# blogs
# -----

GET http://localhost:3001/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "16/9",
  "author": "new newauthor",
  "url": "new new url",
  "likes": "115"
}

###

# users
# -----

GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username":"betoGer",
  "name":"ger",
  "password":"beto"
}